apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: my-image-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "k8s-demo-dev"
      images:
        - alias: "demo-dev"
          imageName: "harbor.sabihinmolang.eu.org/demo/demo-dev:latest"
          commonUpdateSettings:
            pullsecret: k8s-demo-dev/harbor-secret
            updateStrategy: "digest"
