apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: harbor-static-secret
  labels:
    label-to-be-passed-to-managed-secret: sample-value
  annotations:
    example.com/annotation-to-be-passed-to-managed-secret: "sample-value"
spec:
  infisicalAuthRef:
    name: my-infisical-auth
    namespace: default

  syncOptions:
    refreshInterval: 60s
    instantUpdates: false

  sources:
    - projectId: d4e69013-ff8c-4c92-b07d-18d6a83d234c
      environmentSlug: dev
      secretPath: /

  targets:
    - name: harbor-secret
      namespace: {{ .Release.Namespace }}
      kind: Secret
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "{{`{{ .HARBOR_REGISTRY.Value }}`}}": {
                  "username": "{{`{{ .HARBOR_USERNAME.Value }}`}}",
                  "password": "{{`{{ .HARBOR_PASSWORD.Value }}`}}",
                  "email": "{{`{{ .HARBOR_EMAIL.Value }}`}}",
                  "auth": "{{`{{ printf "%s:%s" (.HARBOR_USERNAME.Value) (.HARBOR_PASSWORD.Value) | b64enc }}`}}"
                }
              }
            }

